language: php

addons:
  apt:
    packages:
      - redis-server
services:
  - redis-server
before_install:
  - sudo sed -e 's/^bind.*/bind 127.0.0.1/' /etc/redis/redis.conf > redis.conf
  - sudo mv redis.conf /etc/redis
  - sudo service redis-server start
  - printf "\n" | pecl install -f redis
before_script:
  - composer require "orchestra/testbench=${testbench}" --dev --prefer-dist --no-interaction --no-suggest
  - composer require "laravel/framework=${laravel}" --dev --prefer-dist --no-interaction --no-suggest
  - composer install --prefer-source --no-interaction
  - composer du

script:
  - vendor/bin/phpunit

matrix:
  include:
    - php: 7.2
      env: laravel=^6.0 testbench=^4.0
    - php: 7.2
      env: laravel=^7.0 testbench=^5.0
    - php: 7.3
      env: laravel=^6.0 testbench=^4.0
    - php: 7.3
      env: laravel=^7.0 testbench=^5.0
    - php: 7.3
      env: laravel=^8.0 testbench=^6.0
    - php: 7.4
      env: laravel=^7.0 testbench=^5.0
    - php: 7.4
      env: laravel=^8.0 testbench=^6.0

  fast_finish: true